
title: BallCuber
description: This machine can solve the 4x4x4 Rubiks's Cube !
owner: Your Name 
first_published: 2020 
email: your-email@domain.com
baseurl: "" 
url: "https://ballcuber.github.io"
social:
  #twitter:
  github: https://github.com/ballcuber
  #linkedin-square:
  #facebook-official: 
  #google-plus-square:
  #email:
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
