
title: The BallCuber
description: This machine can solve the 4x4x4 Rubiks's Cube !
owner: BallCuber
first_published: 2020 
email: 
baseurl: "" 
url: "https://ballcuber.github.io"

onshape: "https://cad.onshape.com/documents/0cc05df50afa7069d40d5b29/w/4e9a02bde82a52420bb553ee/e/6d739c0ee09a45d88f809d15"

social:
  #twitter:
  github: https://github.com/ballcuber
  #linkedin-square:
  #facebook-official: 
  #google-plus-square:
  #email:
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
